#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deadlock-index"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"

[experimental]
auto_rollback = true

[http_service]
internal_port = 3000
processes = ["app"]
protocol = "tcp"
min_machines_running = 0
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true

[http_service.concurrency]
hard_limit = 100
soft_limit = 90
type = "connections"

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
